# Numpy: The heart of scientific computing

* All the Data Science libraries are based on NumPy (Like pandas, scipy, matplotlib, sklearn, tensorflow)
* Mainly creates an n-dimensional array
![](np_array.PNG)

<font color='red'>**Why not list then?**</font>

**1. Numpy is faster**

a. Uses less memory 
see more : https://stackoverflow.com/questions/51240086/how-does-python-numpy-save-memory-compared-to-a-list

b. No need to type-check while iterating

c. Numpy has contiguous memory blocks, meaning, unlike lists, the memory blocks are next to each other

**2. NumPy has many more functionalities including that of in Lists**

## start the code

In [1]:
# to install: pip install numpy or pip3 install numpy 
# for notebooks: "!pip install numpy"
import numpy as np

In [2]:
V = np.array([1, 13, 2.99, 45, 8])
print(V)
print("The dimension of V array is", V.ndim)

[ 1.   13.    2.99 45.    8.  ]
The dimension of V array is 1


**writing multidimensional array**

<font color = 'magenta'>ARRAY = np.array( [row1, row2,... rown] )</font> --> All the rows have to be of same length.

In [3]:
A = np.array([[1, 2, 3, 4],[8, 9, 10, 11], [15, 16, 17, 18]])
print(A)

[[ 1  2  3  4]
 [ 8  9 10 11]
 [15 16 17 18]]


In [4]:
A.ndim

2

In [5]:
# An interesting 3-D array
A_3d = np.array([[[0,0,0,0,1], [0,0,0,1,0], [0,0,0,1,1], [1,0,0,1,0]],
                 [[0,1,0,0,0], [0,1,0,0,0], [0,1,0,1,0], [0,1,0,1,1]], 
                 [[0,1,1,1,1], [1,0,0,0,0], [1,0,0,0,1], [1,0,0,1,0]]])
print(A_3d)
print("\n**************\n")
print("Dimension of the A_3d matrix is", A_3d.ndim)


[[[0 0 0 0 1]
  [0 0 0 1 0]
  [0 0 0 1 1]
  [1 0 0 1 0]]

 [[0 1 0 0 0]
  [0 1 0 0 0]
  [0 1 0 1 0]
  [0 1 0 1 1]]

 [[0 1 1 1 1]
  [1 0 0 0 0]
  [1 0 0 0 1]
  [1 0 0 1 0]]]

**************

Dimension of the A_3d matrix is 3


In [6]:
# shape of the array
print("The shape of the array V is", V.shape)
print("The shape of the array A is", A.shape)
print("The shape of the array A_3d is", A_3d.shape)

The shape of the array V is (5,)
The shape of the array A is (3, 4)
The shape of the array A_3d is (3, 4, 5)


**type and size of the array**

In [7]:
type(A)

numpy.ndarray

In [8]:
A.dtype #the data type of the values in array A

dtype('int32')

In [9]:
# we can redefine that
A_redefined = np.array([[1, 2, 3, 4],[8, 9, 10, 11], [15, 16, 17, 18]], dtype='int8')
A_redefined.dtype

dtype('int8')

In [10]:
A.nbytes

48

In [11]:
A_redefined.nbytes

12

## Access value in the array

In [13]:
A

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11],
       [15, 16, 17, 18]])

In [ ]:
A[2,3] #third row, fourth column

In [15]:
A[-2, -2] #second from the last row and second from the last column

10

In [17]:
A[1,:] # will print the second row as a vector

array([ 8,  9, 10, 11])

In [18]:
A[:, 3] # all the element of the fourth column

array([ 4, 11, 18])

In [19]:
#iterating
A[2, 0:4:2]  # print the third row but iterate that in every two element

array([15, 17])

In [20]:
# replace element 
A_cp = A.copy() #later
A_cp[1,:] = [1, 4, 9, 16] # you can do that without making an array
A_cp

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16],
       [15, 16, 17, 18]])

In [21]:
# what if we replace with a float?
A_cp[1,:] = [1.88, 4, 9.33, 16]
A_cp

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16],
       [15, 16, 17, 18]])

In [27]:
simple = np.array([[1,2], [3,4]], dtype='int32')
simple[0,:] = [0.99, 1.89]
simple

array([[0, 1],
       [3, 4]])

**It didn't change!**

In [28]:
A_cp.dtype

dtype('int32')

In [29]:
A_cp_float = A_cp.astype('float')
A_cp_float

array([[ 1.,  2.,  3.,  4.],
       [ 1.,  4.,  9., 16.],
       [15., 16., 17., 18.]])

In [30]:
A_cp_float[1,:] = [1.88, 4, 9.33, 16]
A_cp_float

array([[ 1.  ,  2.  ,  3.  ,  4.  ],
       [ 1.88,  4.  ,  9.33, 16.  ],
       [15.  , 16.  , 17.  , 18.  ]])

In [ ]:
A_cp_float.dtype

## Initialization matrices

In [31]:
All_ones = np.ones((4,6))
All_ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
All_zeros = np.zeros((4,6))
All_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
All_5s = np.full((3,8), 5)
All_5s

array([[5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [34]:
# random number
rand_array = np.random.rand(4,2) # notice the difference between all zeros or all ones and this one
rand_array

array([[0.48557178, 0.92949923],
       [0.12927275, 0.76135243],
       [0.136967  , 0.6315703 ],
       [0.5498768 , 0.63562025]])

In [40]:
rand_array = np.random.randint(-3, 10, size = (7,3)) # A random array that values take between -3 to 9
rand_array

array([[-2,  6, -3],
       [ 7,  3,  1],
       [ 3, -1,  9],
       [ 2,  7,  9],
       [ 2, -3,  9],
       [ 9,  9,  6],
       [ 2,  0,  3]])

In [43]:
# Random seed
np.random.seed(23)
rand_array = np.random.randint(-3, 10, size = (7,3)) # A random array that values take between -3 to 9
rand_array

array([[ 0,  3,  5],
       [ 6,  3,  5],
       [ 9,  8,  4],
       [ 7,  6,  0],
       [ 3,  8,  9],
       [-2, -1,  8],
       [ 2,  2, -3]])

In [78]:
np.random.uniform(low=0.5, high=13.3, size=(10,))

array([ 1.91411474,  0.50676878, 12.55972778,  2.3112097 ,  5.89643553,
        4.93506483, 11.63324908,  5.9861032 , 11.108019  ,  9.68850353])

In [47]:
# identity matrix
iden_array = np.identity(15) # creates a nXn identity matrix 
iden_array

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [50]:
# repeat matrix
C = np.array([[2,3,4]])
C_repeated = np.repeat(C, 3, axis=0) # axis 0 means, repeat the rows. axis 1 means, repeat the columns
print(C_repeated)

[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [51]:
np.repeat(A, 3, axis=1)

array([[ 1,  1,  1,  2,  2,  2,  3,  3,  3,  4,  4,  4],
       [ 8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11],
       [15, 15, 15, 16, 16, 16, 17, 17, 17, 18, 18, 18]])

## copy method

In [52]:
D = np.array([[2,3,5,7],[11,13,17,19],[23,29,31,37]])
D

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [23, 29, 31, 37]])

In [53]:
D_equal = D
D_equal[2,:] = [0, 0, 0, 0]
D_equal

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [ 0,  0,  0,  0]])

In [54]:
D

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [ 0,  0,  0,  0]])

<font color = 'red'>We can see that D has changed as well !</font>

In [55]:
D_cp = D.copy()
D_cp[2,:] = [1, 0, 1, 1]
D

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [ 0,  0,  0,  0]])

In [56]:
D_cp

array([[ 2,  3,  5,  7],
       [11, 13, 17, 19],
       [ 1,  0,  1,  1]])

## Computation

In [57]:
AR1 = np.array([[2,33,4], [1, 18, 99]])
AR2 = np.array([[21,3,13], [29, 8, 9]])
print(AR1 + AR2) # element to element add
print('***************')
print(AR1-AR2) # element to element subtract
print('***************')
print(AR1*AR2)# element to element multiplication
print('***************')
print(AR1/AR2)# element to element division

[[ 23  36  17]
 [ 30  26 108]]
***************
[[-19  30  -9]
 [-28  10  90]]
***************
[[ 42  99  52]
 [ 29 144 891]]
***************
[[ 0.0952381  11.          0.30769231]
 [ 0.03448276  2.25       11.        ]]


In [70]:
## broadcasting the array
print(AR1 + 12) # makes an array of same size of AR1 and then adds it
print('***************')
print(AR1 + np.array([[1, 12, 1]])) #copy the row and then adds it
print('***************')

[[ 14  45  16]
 [ 13  30 111]]
***************
[[  3  45   5]
 [  2  30 100]]
***************


In [74]:
#the sin/cos are also here!
np.sin(3.141592653/2)

1.0

## Dealing with Linear Algebra

In [60]:
A1 = np.array([[2,3,4],[4,1,1]]) # A 2X3 matrix
A2 = np.array([[2,3,4,9],
               [4,1,1,6],
               [2,1,1,1]]) # A 3X4 matrix
np.matmul(A1, A2) # we will have a 2X4 matrix

array([[24, 13, 15, 40],
       [14, 14, 18, 43]])

In [61]:
# Find the determinant
B1 = np.array([[1,3],[-2,4]])
np.linalg.det(B1)

9.999999999999998

Even more: https://numpy.org/doc/stable/reference/routines.linalg.html

## Statistical calculations

In [68]:
A2

array([[2, 3, 4, 9],
       [4, 1, 1, 6],
       [2, 1, 1, 1]])

In [62]:
print(np.mean(A2, axis = 0)) # move row-wise 
print(np.mean(A2, axis = 1)) # move column wise
print(np.mean(A2)) #mean of all values


[2.66666667 1.66666667 2.         5.33333333]
[4.5  3.   1.25]
2.9166666666666665


Explore min, max, quantile and so on...

## Organizing an array

In [63]:
A2

array([[2, 3, 4, 9],
       [4, 1, 1, 6],
       [2, 1, 1, 1]])

In [66]:
## Reshaping an array
A2.reshape(12,1)


array([[2],
       [3],
       [4],
       [9],
       [4],
       [1],
       [1],
       [6],
       [2],
       [1],
       [1],
       [1]])

In [69]:
## stacking up the rows
R1 = np.array([[2, 3.1, 3]])
R2 = np.array([[9, 11, 13]])
print(np.vstack((R1,R2, R1)))
print(np.hstack((R1,R2)))

[[ 2.   3.1  3. ]
 [ 9.  11.  13. ]
 [ 2.   3.1  3. ]]
[[ 2.   3.1  3.   9.  11.  13. ]]
